# Generated by Django 3.2.7 on 2021-10-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='タイトル')),
                ('created_at', models.CharField(max_length=128, verbose_name='投稿時刻')),
                ('movie_id', models.CharField(max_length=128, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='タイトル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('text', models.TextField(verbose_name='本文')),
                ('image', models.ImageField(upload_to='images/', verbose_name='ニュース画像')),
            ],
        ),
    ]
