# Generated by Django 3.2.7 on 2021-10-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link_text',
            field=models.CharField(blank=True, max_length=128, verbose_name='リンク先'),
        ),
        migrations.AddField(
            model_name='news',
            name='link_url',
            field=models.CharField(blank=True, max_length=128, verbose_name='URL'),
        ),
    ]
