# Generated by Django 3.2.7 on 2021-10-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211014_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='タイトル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('text', models.TextField(verbose_name='本文')),
                ('image', models.ImageField(upload_to='images/', verbose_name='ニュース画像')),
                ('link_url', models.CharField(max_length=128, verbose_name='URL')),
                ('link_text', models.CharField(max_length=128, verbose_name='リンク先')),
            ],
        ),
    ]
