# Generated by Django 3.2.7 on 2021-10-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_essay'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='title',
            field=models.CharField(blank=True, max_length=128, verbose_name='タイトル'),
        ),
    ]
