# Generated by Django 3.2.7 on 2021-10-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_edit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notice_bbs',
            field=models.BooleanField(default=False, verbose_name='投稿通知'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notice_comment',
            field=models.BooleanField(default=False, verbose_name='コメント通知'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notice_like',
            field=models.BooleanField(default=False, verbose_name='いいね通知'),
        ),
    ]
